name: "Take QEMU screenshot"
description: "Take QEMU screenshot and upload with PR comment"
runs:
  using: "composite"
  steps:
      - name: Take QEMU screenshot
        shell: bash
        run: |
          # Dump framebuffer to PPM via QEMU monitor
          echo "screendump /tmp/vm.ppm" | sudo socat - UNIX-CONNECT:/tmp/qemu-monitor-sock

          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends imagemagick

          # Convert PPM → PNG
          sudo convert /tmp/vm.ppm /tmp/vm.png

      - name: Upload screenshot as artifact
        id: screenshot
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: vm-screenshot
          path: /tmp/vm.png

      - name: create screenshot pr comment
        shell: bash
        run: |
          echo '## 🖼 VM Screenshot' >> screenshot.md
          echo '' >> screenshot.md
          echo '${{ steps.screenshot.outputs.artifact-url }}' >> screenshot.md

      - name: Sticky PR comment (update in-place)
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2
        with:
          path: screenshot.md
          skip_unchanged: true
          header: screenshot