#!/usr/bin/env bash

USER_HOOKS_DIRECTORY="/usr/share/bootc/user-setup.hooks.d"

# Privileged setup can be called via user services
if [ -d "$USER_HOOKS_DIRECTORY" ] ; then
	for script in $USER_HOOKS_DIRECTORY/* ; do
		bash $script
	done
fi