name: "Create PR report"
description: "Generate a report for the PR"
runs:
  using: "composite"
  steps:
    - name: Inspect images (Podman)
      id: meta
      shell: bash
      run: | #sh
        set -euo pipefail

        BASE_RAW=$(podman image inspect ${{ env.IMAGE_FULL }}:latest | jq '.[0]')
        PR_RAW=$(podman image inspect "${{ env.IMAGE_FULL }}:${{ env.DOCKER_TAG }}" | jq '.[0]')

        BASE_DIGEST=$(jq -r '.Digest // empty' <<<"$BASE_RAW")
        PR_DIGEST=$(jq -r '.Digest // empty' <<<"$PR_RAW")
        BASE_CREATED=$(jq -r '.Created // "n/a"' <<<"$BASE_RAW")
        PR_CREATED=$(jq -r '.Created // "n/a"' <<<"$PR_RAW")
        BASE_SIZE=$(jq -r '.Size // 0' <<<"$BASE_RAW")
        PR_SIZE=$(jq -r '.Size // 0' <<<"$PR_RAW")
        BASE_LAYERS=$(jq -r '.RootFS.Layers | length' <<<"$BASE_RAW")
        PR_LAYERS=$(jq -r '.RootFS.Layers | length' <<<"$PR_RAW")

        BASE_KEYS=$(jq -r '.Labels | keys[]?' <<<"$BASE_RAW" | sort || true)
        PR_KEYS=$(jq -r '.Labels | keys[]?' <<<"$PR_RAW" | sort || true)
        LABELS_CHANGED=$(comm -3 <(printf "%s\n" "$BASE_KEYS") <(printf "%s\n" "$PR_KEYS") | paste -sd, -)
        [[ -z "$LABELS_CHANGED" ]] && LABELS_CHANGED="_none_"

        echo "base_digest=$BASE_DIGEST" >> $GITHUB_OUTPUT
        echo "pr_digest=$PR_DIGEST" >> $GITHUB_OUTPUT
        echo "base_created=$BASE_CREATED" >> $GITHUB_OUTPUT
        echo "pr_created=$PR_CREATED" >> $GITHUB_OUTPUT
        echo "base_size=$BASE_SIZE" >> $GITHUB_OUTPUT
        echo "pr_size=$PR_SIZE" >> $GITHUB_OUTPUT
        echo "base_layers=$BASE_LAYERS" >> $GITHUB_OUTPUT
        echo "pr_layers=$PR_LAYERS" >> $GITHUB_OUTPUT
        echo "labels_changed=$LABELS_CHANGED" >> $GITHUB_OUTPUT

    - name: Build report
      id: report
      shell: bash
      run: | #sh
        set -euo pipefail
        base_size=${{ steps.meta.outputs.base_size }}
        pr_size=${{ steps.meta.outputs.pr_size }}
        base_h=$(numfmt --to=iec --suffix=B "$base_size")
        pr_h=$(numfmt --to=iec --suffix=B "$pr_size")
        delta=$(( pr_size - base_size ))
        abs=${delta#-}
        delta_h=$(numfmt --to=iec --suffix=B "$abs")
        if   [[ $delta -gt 0 ]]; then trend="+${delta_h}"
        elif [[ $delta -lt 0 ]]; then trend="-${delta_h}"
        else trend="±0"; fi

        base_set=$(jq -r '[.Results[]?.Vulnerabilities[]? | .VulnerabilityID] | unique[]?' latest_trivy.json | sort || true)
        pr_set=$(jq -r   '[.Results[]?.Vulnerabilities[]? | .VulnerabilityID] | unique[]?' current_trivy.json   | sort || true)
        new=$(comm -13 <(printf "%s\n" "$base_set") <(printf "%s\n" "$pr_set") | sort || true)
        fix=$(comm -23 <(printf "%s\n" "$base_set") <(printf "%s\n" "$pr_set") | sort || true)
        new_n=$(printf "%s\n" "$new" | grep -c . || true)
        fix_n=$(printf "%s\n" "$fix" | grep -c . || true)
        new_top=$(printf "%s\n" "$new" | head -n 5 | paste -sd, -)
        [[ -z "$new_top" ]] && new_top="_none_"

        {
          echo "### 🧾 Image diff"
          echo
          echo "**Repo:** ghcr.io/${{ github.repository }}"
          echo "**Base:** \`${{ env.IMAGE_FULL }}:latest\` (digest: ${{ steps.meta.outputs.base_digest || 'n/a' }})"
          echo "**PR:** \`${{ env.LOCAL_PR_IMAGE }}\` (digest: ${{ steps.meta.outputs.pr_digest || 'n/a' }})"
          #echo "- Trivy CVEs: ${pr_set}"
          echo
          echo "- Created: ${{ steps.meta.outputs.base_created }} → ${{ steps.meta.outputs.pr_created }}"
          echo "- Size (compressed): ${base_h} → ${pr_h} (**${trend}**)"
          echo "- Layers: ${{ steps.meta.outputs.base_layers }} → ${{ steps.meta.outputs.pr_layers }}" # (**${layer_delta}**)
          echo "- Labels changed: ${{ steps.meta.outputs.labels_changed }}"
          echo "- Trivy HIGH/CRIT: +${new_n} / -${fix_n} (new: ${new_top})"
        } > comment.md

    - name: Sticky PR comment (update in-place)
      uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2
      with:
        path: comment.md
        skip_unchanged: true
        header: "🧾 Image diff for ${{ env.IMAGE_FULL }}"
