name: "Cleanup image"
description: "Cleanup dangling images etc."
runs:
  using: "composite"
  steps:
    - name: Cleanup
      if: ${{ runner.environment == 'self-hosted' }}
      shell: bash
      run: |
        sudo podman rmi -i ${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}
        sudo podman rmi -i ${{ env.LOCAL_PR_IMAGE }}
        sudo podman rmi -i localhost:5000/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}

        podman rmi -i ${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}
        podman rmi -i ${{ env.LOCAL_PR_IMAGE }}
        podman rmi -i localhost:5000/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}

    - name: List images
      shell: bash
      run: |
        echo "Root:"
        sudo podman images
        echo "Rootless:"
        podman images
