name: "Upload trivy scan results to github"
description: "Upload trivy scan results to GitHub Security tab"
inputs:
  github_token:
    description: "Token with permissions to push/copy images (pass secrets.GITHUB_TOKEN or a PAT)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Trivy REPORT sarif (base:latest)
      uses: aquasecurity/trivy-action@e368e328979b113139d6f9068e03accaed98a518 # 0.34.1
      with:
        image-ref: ${{ env.LOCAL_PR_IMAGE }}
        ignore-unfixed: true
        #severity: HIGH,CRITICAL
        format: "sarif"
        output: "trivy-results.sarif"
        skip-setup-trivy: true
        scanners: "vuln"
        vuln-type: "library"
        severity: "CRITICAL,HIGH,MEDIUM"
        cache: "false"
      env:
        TRIVY_SKIP_DB_UPDATE: true
        TRIVY_SKIP_JAVA_DB_UPDATE: true

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@0499de31b99561a6d14a36a5f662c2a54f91beee # v4
      with:
        token: ${{ inputs.github_token }}
        sarif_file: "${{ github.workspace }}/trivy-results.sarif"
        category: trivy

    - name: Trivy SBOM - current
      uses: aquasecurity/trivy-action@e368e328979b113139d6f9068e03accaed98a518 # 0.34.1
      with:
        image-ref: ${{ env.LOCAL_PR_IMAGE }}
        scan-type: image
        format: "github"
        output: "${{ github.workspace }}/dependency-results.sbom.json"
        github-pat: ${{ inputs.github_token }}
        scanners: "vuln"
        skip-setup-trivy: true
        vuln-type: "library"
        severity: "CRITICAL,HIGH,MEDIUM"
        cache: "false"
      env:
        TRIVY_SKIP_DB_UPDATE: true
        TRIVY_SKIP_JAVA_DB_UPDATE: true

    - name: Upload trivy report as a Github artifact
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      with:
        name: trivy-${{ matrix.image }}-sbom-report
        path: "${{ github.workspace }}/dependency-results.sbom.json"
        retention-days: 20 # 90 is the default
