name: "Upload trivy scan results to github"
description: "Upload trivy scan results to GitHub Security tab"
inputs:
  github_token:
    description: "Token with permissions to push/copy images (pass secrets.GITHUB_TOKEN or a PAT)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Trivy REPORT sarif (base:latest)
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
      with:
        image-ref: ${{ env.LOCAL_PR_IMAGE }}
        ignore-unfixed: true
        #severity: HIGH,CRITICAL
        format: "sarif"
        output: "trivy-results.sarif"
        skip-setup-trivy: true
        scanners: "vuln"
        vuln-type: "library"
        severity: "CRITICAL,HIGH,MEDIUM"
        cache: "false"
      env:
        TRIVY_SKIP_DB_UPDATE: true
        TRIVY_SKIP_JAVA_DB_UPDATE: true

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13 # v4.35.1
      with:
        token: ${{ inputs.github_token }}
        sarif_file: "${{ github.workspace }}/trivy-results.sarif"
        category: trivy

    - name: Trivy SBOM - current
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
      with:
        image-ref: ${{ env.LOCAL_PR_IMAGE }}
        scan-type: image
        format: "github"
        output: "${{ github.workspace }}/dependency-results.sbom.json"
        github-pat: ${{ inputs.github_token }}
        scanners: "vuln"
        skip-setup-trivy: true
        vuln-type: "library"
        severity: "CRITICAL,HIGH,MEDIUM"
        cache: "false"
      env:
        TRIVY_SKIP_DB_UPDATE: true
        TRIVY_SKIP_JAVA_DB_UPDATE: true

    - name: Upload trivy report as a Github artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: trivy-${{ matrix.image }}-sbom-report
        path: "${{ github.workspace }}/dependency-results.sbom.json"
        retention-days: 20 # 90 is the default
