name: "Ensure trivy is installed and DB is cached"
description: "Ensure trivy is installed and its database is cached for faster scans"
inputs:
  trivy_version:
    description: 'TRIVY_VERSION'
    required: true
    default: '0.69.3'
runs:
  using: composite
  steps:
    - name: Get current date
      shell: bash
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Setup trivy
      shell: bash
      run: |
        set -euo pipefail

        version="${{ env.TRIVY_VERSION }}"
        arch=amd64
        install_dir="$HOME/.local/bin"
        mkdir -p "$install_dir"

        curl -sL \
          "https://github.com/aquasecurity/trivy/releases/download/v${version}/trivy_${version}_Linux-64bit.tar.gz" \
          -o "$install_dir/trivy.tar.gz"
        tar -xzf "$install_dir/trivy.tar.gz" -C "$install_dir"
        chmod +x "$install_dir/trivy"
        echo "$install_dir" >> "$GITHUB_PATH"

    - name: Restore DB from cache
      uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      if: ${{ runner.environment != 'self-hosted' }}
      with:
        path: ${{ github.workspace }}/.cache/trivy
        key: cache-trivy-${{ steps.date.outputs.date }}
        restore-keys: cache-trivy-

    # rely on pull-through cache on self-hosted runners
    - name: Download and extract the vulnerability DB
      shell: bash
      if: ${{ runner.environment == 'self-hosted' }}
      run: |
        mkdir -p $GITHUB_WORKSPACE/.cache/trivy/db
        oras pull localhost:5005/aquasecurity/trivy-db:2
        tar -xzf db.tar.gz -C $GITHUB_WORKSPACE/.cache/trivy/db
        rm db.tar.gz

    - name: Download and extract the Java DB
      if: ${{ runner.environment == 'self-hosted' }}
      shell: bash
      run: |
        mkdir -p $GITHUB_WORKSPACE/.cache/trivy/java-db
        oras pull localhost:5005/aquasecurity/trivy-java-db:1
        tar -xzf javadb.tar.gz -C $GITHUB_WORKSPACE/.cache/trivy/java-db
        rm javadb.tar.gz
