name: "Load latest image to speed up build"
description: "Load latest image to speed up build"
runs:
  using: "composite"
  steps:
    - name: Configure containers storage.conf
      shell: bash
      run: |
        mkdir -p ~/.config/containers
        sudo mkdir -p /var/lib/shared
        sudo chmod -R a+rx /var/lib/shared
        sudo chown -R $(whoami):$(whoami) /var/lib/shared

        cat > ~/.config/containers/storage.conf <<'EOF'
        [storage]
        driver = "overlay"

        [storage.options]
        additionalimagestores = [ "/var/lib/shared",]

        [storage.options.overlay]
        mount_program = "/usr/bin/fuse-overlayfs"
        EOF

        # workaround https://github.com/containers/podman/issues/21683
        echo "update DBConfig set GraphDriver = 'overlay' where GraphDriver = '';" | sudo sh -c '(cd /home/runner/.local/share/containers/storage && sqlite3 db.sql)'

    - name: Load latest image to speed up build
      shell: bash
      if: "false"
      run: | #sh
        podman images
        podman --root /var/lib/shared pull -q ${{ env.IMAGE_FULL }}:latest || true
        sudo chmod -R a+rx /var/lib/shared # podman bug workaround
        podman images

    - name: Move cache to local storage
      shell: bash
      if: "false"
      #if: ${{ runner.environment  == 'self-hosted' }}
      run: | #sh
        sudo apt-get update -qq
        sudo apt-get install -y skopeo
        skopeo copy \
          containers-storage:${{ env.IMAGE_FULL }}:latest \
          containers-storage:localhost/${{ env.IMAGE_NAME }}:latest

    - name: Push to local registry
      shell: bash
      if: "false" # Disable for now
      run: | #sh
        # Start a local registry
        podman run -d --name local-registry \
          -p 5000:5000 \
          -v registry-data:/var/lib/registry \
          docker.io/library/registry:2

        # Tag the image for the local registry 
        podman tag ${{ env.IMAGE_FULL }}:latest 127.0.0.1:5000/${{ env.IMAGE_NAME }}:latest

        # Push to the local registry without tls
        podman push --tls-verify=false 127.0.0.1:5000/${{ env.IMAGE_NAME }}:latest

    - name: Enable Podman socket
      shell: bash
      run: | #sh
        install -d -m 700 "$XDG_RUNTIME_DIR/podman"
        loginctl enable-linger $(whoami) || true
        sleep 1
        podman system service --time=0 "unix://$XDG_RUNTIME_DIR/podman/podman.sock" &
        export CONTAINER_HOST="unix://$XDG_RUNTIME_DIR/podman/podman.sock"
        echo "CONTAINER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock" >> $GITHUB_ENV
        #podman info
        #podman images ls

    - name: Enabled buildah support
      shell: bash
      run: | #sh
        sudo apt-get update
        sudo apt-get install -y buildah uidmap slirp4netns fuse-overlayfs
        mkdir -p /home/runner/.cache/dnf
