name: "Run QEMU tests"
description: "Run QEMU tests on the built image"
inputs:
  SSH_USERNAME:
    description: "SSH_USERNAME for runner account"
    required: true
  SSH_KEY:
    description: "SSH_KEY for runner account"
    required: true
  SSH_PRIVATE_KEY:
    description: "SSH_PRIVATE_KEY used by personal account"
    required: true
  SSH_OPTIONS:
    description: "SSH_OPTIONS"
    required: true
runs:
  using: "composite"
  steps:
    - name: Wait for SSH
      uses: ./.github/actions/ssh-ping
      with:
        SSH_KEY: ${{ inputs.SSH_KEY }}
        SSH_USERNAME: ${{ inputs.SSH_USERNAME }}
        SSH_OPTIONS: ${{ inputs.SSH_OPTIONS }}

    - name: Run startup checks
      shell: bash
      env:
        SSH_KEY: ${{ inputs.SSH_KEY }}
        SSH_USERNAME: ${{ inputs.SSH_USERNAME }}
        SSH_OPTIONS: ${{ inputs.SSH_OPTIONS }}
      run: | #sh
        # turn the env string into a Bash array
        read -ra SSH_OPTS <<< "${{ env.SSH_OPTIONS }}"

        # Make sure VM is ready for testing
        echo "--- system is-running ---"
        ssh "${SSH_OPTS[@]}" \
          -i "$SSH_KEY" \
          -p 2222 \
          ${SSH_USERNAME}@localhost \
          "sudo bootc status"

        echo "--- rpm-ostree status ---"
        ssh "${SSH_OPTS[@]}" \
          -i "$SSH_KEY" \
          -p 2222 \
          ${SSH_USERNAME}@localhost \
          "rpm-ostree status"

        echo "--- systemctl is-system-running ---"
        ssh "${SSH_OPTS[@]}" \
          -i "$SSH_KEY" \
          -p 2222 \
          ${SSH_USERNAME}@localhost \
          "timeout 30 systemctl is-system-running --wait || systemctl --failed"

        echo "--- stats ---"
        ssh "${SSH_OPTS[@]}" \
          -i "$SSH_KEY" \
          -p 2222 \
          ${SSH_USERNAME}@localhost \
          "df -h"

        echo "--- fastfetch ---"
        ssh "${SSH_OPTS[@]}" \
          -i "$SSH_KEY" \
          -p 2222 \
          ${SSH_USERNAME}@localhost \
          "fastfetch || true"

    - name: Reboot VM
      if: false
      shell: bash
      env:
        SSH_KEY: ${{ inputs.SSH_KEY }}
        SSH_USERNAME: ${{ inputs.SSH_USERNAME }}
        SSH_OPTIONS: ${{ inputs.SSH_OPTIONS }}
      run: | #sh
        # turn the env string into a Bash array
        read -ra SSH_OPTS <<< "${{ env.SSH_OPTIONS }}"

        ssh "${SSH_OPTS[@]}" \
          -i "$SSH_KEY" \
          -p 2222 \
          ${SSH_USERNAME}@localhost \
          "sudo reboot"

    - name: Wait on reboot
      uses: ./.github/actions/ssh-ping
      if: false
      with:
        SSH_KEY: ${{ inputs.SSH_KEY }}
        SSH_USERNAME: ${{ inputs.SSH_USERNAME }}
        SSH_OPTIONS: ${{ inputs.SSH_OPTIONS }}

    - name: Run diagnostics
      shell: bash
      env:
        SSH_KEY: ${{ inputs.SSH_KEY }}
        SSH_USERNAME: ${{ inputs.SSH_USERNAME }}
        SSH_OPTIONS: ${{ inputs.SSH_OPTIONS }}
      run: | #sh
        # turn the env string into a Bash array
        read -ra SSH_OPTS <<< "${{ env.SSH_OPTIONS }}"

        cat ./tests/diagnostics.sh | ssh "${SSH_OPTS[@]}" \
          -i "${SSH_KEY}" \
          -p 2222 \
          ${SSH_USERNAME}@localhost

    - name: Run system tests
      shell: bash
      env:
        SSH_KEY: ${{ inputs.SSH_KEY }}
        SSH_USERNAME: ${{ inputs.SSH_USERNAME }}
        SSH_OPTIONS: ${{ inputs.SSH_OPTIONS }}
      run: | #sh
        # turn the env string into a Bash array
        read -ra SSH_OPTS <<< "${{ env.SSH_OPTIONS }}"

        cat ./tests/${{ matrix.image }}/system-test.sh | ssh "${SSH_OPTS[@]}" \
          -i "${SSH_KEY}" \
          -p 2222 \
          ${SSH_USERNAME}@localhost

    - name: Run user tests
      shell: bash
      env:
        SSH_USERNAME: caspertdk
        SSH_KEY: ${{ inputs.SSH_PRIVATE_KEY }}
        SSH_OPTIONS: ${{ inputs.SSH_OPTIONS }}
      run: | #sh
        # turn the env string into a Bash array
        read -ra SSH_OPTS <<< "${{ env.SSH_OPTIONS }}"

        if [ -e ./tests/${{ matrix.image }}/user-test.sh ]; then
          cat ./tests/${{ matrix.image }}/user-test.sh | ssh "${SSH_OPTS[@]}" \
            -i "${SSH_KEY}" \
            -p 2222 \
            ${SSH_USERNAME}@localhost \
            bash -l -s --
        fi

    - name: Verify ghcr.io auth
      shell: bash
      if: ${{ startsWith(matrix.image, 'homeserver') }}
      env:
        SSH_USERNAME: caspertdk
        SSH_KEY: ${{ inputs.SSH_PRIVATE_KEY }}
        SSH_OPTIONS: ${{ inputs.SSH_OPTIONS }}
        IMAGE_FULL: ${{ env.IMAGE_FULL }}
      run: | #sh
        # turn the env string into a Bash array
        read -ra SSH_OPTS <<< "${{ env.SSH_OPTIONS }}"
        cat ./tests/verify-cosign.sh | ssh "${SSH_OPTS[@]}" \
          -i "$SSH_KEY" \
          -p 2222 \
          "$SSH_USERNAME"@localhost \
            IMAGE_FULL="ghcr.io/cthtrifork/homeserver-bootc/hello" \
            bash -l -s --
