name: "Prepare podman"
description: "Prepare Podman for building and loading images"
runs:
  using: "composite"
  steps:
    - name: Configure containers storage.conf
      shell: bash
      run: | #sh
        mkdir -p ~/.config/containers
        sudo mkdir -p /var/lib/shared
        sudo chmod -R a+rx /var/lib/shared
        sudo chown -R $(whoami):$(whoami) /var/lib/shared

        printf "%s\n" \
        "[storage]" \
        'driver = "overlay"' \
        "" \
        "[storage.options]" \
        'additionalimagestores = [ "/var/lib/shared",]' \
        "" \
        "[storage.options.overlay]" \
        'mount_program = "/usr/bin/fuse-overlayfs"' \
        > ~/.config/containers/storage.conf

        # workaround https://github.com/containers/podman/issues/21683
        echo "update DBConfig set GraphDriver = 'overlay' where GraphDriver = '';" | sudo sh -c '(cd /home/runner/.local/share/containers/storage && sqlite3 db.sql)'

    - name: Start a local registry with proxy to ghcr.io
      shell: bash
      if: ${{ runner.environment == 'self-hosted' }}
      run: | #sh
        # Start a local registry
        podman pull -q docker.io/library/registry:3
        sudo mkdir -p /var/lib/registry/local
        sudo chown -R $(whoami):$(whoami) /var/lib/registry/local
        sudo mkdir -p /etc/distribution/
        sudo touch /etc/distribution/config.yml
        printf "%s\n" \
        "proxy:" \
        "  remoteurl: https://ghcr.io" \
        "  username: ${GITHUB_ACTOR}" \
        "  password: ${secrets_GITHUB_TOKEN}" \
        "  ttl: 168h # 7 days" \
        | sudo tee /etc/distribution/config.yml

        podman run -d --name local-registry \
          -p 5000:5000 \
          -v /var/lib/registry/local/:/var/lib/registry \
          -e REGISTRY_PROXY_REMOTEURL=https://ghcr.io \
          -e REGISTRY_PROXY_USERNAME="${GITHUB_ACTOR}" \
          -e REGISTRY_PROXY_PASSWORD="${secrets_GITHUB_TOKEN}" \
          -e REGISTRY_PROXY_TTL=0 \
          -v /etc/distribution/config.yml:/etc/docker/registry/config.yml:ro \
          docker.io/library/registry:3

    - name: Configure rootless Podman mirror for GHCR
      shell: bash
      if: ${{ runner.environment == 'self-hosted' }}
      run: | #sh
        echo "Applying rootless Podman mirror for GHCR to user"
        mkdir -p ~/.config/containers/registries.conf.d

        printf "%s\n" \
          '[[registry]]' \
          'location = "ghcr.io"' \
          '' \
          '  [[registry.mirror]]' \
          '  location = "localhost:5000"' \
          '  insecure = true' \
          > ~/.config/containers/registries.conf.d/ghcr-mirror.conf
          
          echo "Applying rootless Podman mirror for GHCR to root Podman"
          sudo mkdir -p /etc/containers/registries.conf.d
          sudo cp -f ~/.config/containers/registries.conf.d/ghcr-mirror.conf /etc/containers/registries.conf.d/ghcr-mirror.conf

    - name: Load latest image to speed up build
      shell: bash
      run: | #sh
        podman pull -q ${{ env.IMAGE_FULL }}:latest || true

    - name: Load homeserver-centos-bootc:latest image to speed up build
      shell: bash
      if: ${{ runner.environment == 'self-hosted' }}
      run: | #sh
        #
        podman pull -q ghcr.io/${{ github.repository }}/homeserver-centos-bootc:latest || true

    - name: Enable Podman socket
      shell: bash
      run: | #sh
        #
        install -d -m 700 "$XDG_RUNTIME_DIR/podman"
        loginctl enable-linger $(whoami) || true
        sleep 1
        podman system service --time=0 "unix://$XDG_RUNTIME_DIR/podman/podman.sock" &
        export CONTAINER_HOST="unix://$XDG_RUNTIME_DIR/podman/podman.sock"
        echo "CONTAINER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock" >> $GITHUB_ENV

    - name: Enabled buildah support
      shell: bash
      run: | #sh
        #
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends buildah uidmap slirp4netns fuse-overlayfs
        mkdir -p /home/runner/.cache/dnf
