name: "Push image"
description: "Push container images to the registry"
inputs:
  source_ref:
    description: "ref to oci artifact e.g. oci://xxx or docker://ghcr.io/yyy:tag"
    required: true
  additional_tags:
    description: "Space-separated list of tag strings to apply to IMAGE_FULL (e.g. 'latest pr-123')"
    required: false
    default: ""
  auth_file_path:
    description: "auth file"
    required: true
outputs:
  digest: # id of the output
    description: "The digest of the pushed image"
    value: ${{ steps.digest.outputs.digest }}
runs:
  using: "composite"
  steps:
    - name: Push to Container registry
      if: ${{ runner.environment != 'self-hosted' || github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'push') }}
      id: push-to-ghcr
      shell: bash
      run: | #sh
        DEST="${IMAGE_FULL}:${DOCKER_TAG}"
          
        # Push OCI layout directly to GHCR
        sudo skopeo copy \
          --digestfile digest.txt \
          --authfile ${{ inputs.auth_file_path }} \
          --all \
          "${SOURCE}" \
          "docker://${DEST}"

        IMAGE_DIGEST=$(cat digest.txt)
          
        echo "Adding additional tags to ${{ env.IMAGE_FULL }}@${IMAGE_DIGEST}"
        for tag in $TAGS; do
          sudo skopeo copy -q --all \
            --authfile ${{ inputs.auth_file_path }} \
            "docker://${{ env.IMAGE_FULL }}@${IMAGE_DIGEST}" \
            "docker://${{ env.IMAGE_FULL }}:${tag}"
        done
        crane tag "${DEST}" "${UNIQUE_VERSION}"
        
      env:
        TAGS: ${{ inputs.additional_tags }}
        SOURCE: ${{ inputs.source_ref }}

    - name: Push to cache registry
      if: ${{ runner.environment == 'self-hosted' && github.event_name == 'pull_request' }}
      shell: bash
      run: | #sh
        DEST="localhost:5000/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}"
          
        # Push OCI layout directly to GHCR
        sudo skopeo copy \
          --digestfile digest.txt \
          --authfile ${{ inputs.auth_file_path }} \
          --all \
          --dest-tls-verify=false \
          "${SOURCE}" \
          "docker://${DEST}"
      env:
        SOURCE: ${{ inputs.source_ref }}

    - name: Get Digest
      id: digest
      shell: bash
      run: echo "digest=$(cat digest.txt)" >> "${GITHUB_OUTPUT}"
