name: "Load image"
description: "Load container images for the build"
inputs:
  run_as_sudo:
    description: "Run podman with sudo (rootfull)"
    default: false
    required: false
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Set PODMAN command
      id: config
      shell: bash
      run: |
        if [[ "${{ inputs.run_as_sudo }}" == "true" ]]; then
          echo "PODMAN=sudo podman" >> "$GITHUB_ENV"
        else
          echo "PODMAN=podman" >> "$GITHUB_ENV"
        fi

    - name: Load PR image
      if: ${{ runner.environment != 'self-hosted' }}
      shell: bash
      run: |
        $PODMAN pull -q ${{ env.IMAGE_FULL }}:${{ env.DOCKER_TAG }}
        $PODMAN pull -q ${{ env.IMAGE_FULL }}:latest

        $PODMAN tag \
          ${{ env.IMAGE_FULL }}:${{ env.DOCKER_TAG }} \
          ${{ env.LOCAL_PR_IMAGE }}

    - name: Load PR image from cache registry
      if: ${{ runner.environment == 'self-hosted' }}
      shell: bash
      run: |
        $PODMAN pull --tls-verify=false -q \
          localhost:5000/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}

        $PODMAN tag \
          localhost:5000/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }} \
          ${{ env.LOCAL_PR_IMAGE }}

        $PODMAN tag \
          localhost:5000/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }} \
          ${{ env.IMAGE_FULL }}:${{ env.DOCKER_TAG }}

    - name: List images
      shell: bash
      run: |
        $PODMAN images
