name: Cleanup Pull Request Images
on:
  pull_request:
    types:
      - closed
jobs:
  ghcr-cleanup-image:
    name: ghcr cleanup action
    runs-on: ubuntu-latest
    concurrency:
      group: cleanup-images
    permissions:
      actions: write
    steps:
      - name: Delete image
        uses: dataaxiom/ghcr-cleanup-action@f092b48ba3b604b2a83690dc4b2bbb3392e1045f # v1.2.1
        with:
          delete-tags: pr-${{github.event.pull_request.number}}
          packages: homeserver-bootc/homeserver-centos-bootc,homeserver-bootc/homeserver-gui-bootc

      - name: Delete Untagged Images
        uses: dataaxiom/ghcr-cleanup-action@f092b48ba3b604b2a83690dc4b2bbb3392e1045f # v1.2.1
