name: Cleanup Pull Request Images
on:
  pull_request:
    types:
      - closed
jobs:
  ghcr-cleanup-image:
    name: ghcr cleanup action
    runs-on: ubuntu-latest
    concurrency:
      group: cleanup-images
    permissions:
      actions: write
    steps:
      - name: Delete image
        uses: dataaxiom/ghcr-cleanup-action@374e2028c8fb93b7219f3771cd405fab95d3dec4 # v1.2.0
        with:
          delete-tags: pr-${{github.event.pull_request.number}}
          packages: homeserver-bootc/homeserver-centos-bootc,homeserver-bootc/homeserver-gui-bootc

      - name: Delete Untagged Images
        uses: dataaxiom/ghcr-cleanup-action@374e2028c8fb93b7219f3771cd405fab95d3dec4 # v1.2.0
