name: Renovate
permissions:
  contents: read
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *" # workflows runs every 2 hours
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@1a96852b0384df1837619d04c60b2d10d1f9ff08 # v46.1.21
        with:
          token: ${{ secrets.PAT_RENOVATEBOT }}
          configurationFile: .github/workflows/renovate-config.js
        env:
          RENOVATE_PAT_TOKEN: '${{ secrets.PAT_RENOVATEBOT }}'
          RENOVATE_PLATFORM_COMMIT: 'true'
          RENOVATE_X_GITHUB_HOST_RULES: 'true'
          LOG_LEVEL: debug
