name: Renovate
permissions:
  contents: read
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *" # workflows runs every 2 hours
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@8217b3fc286df088d7c27f3255fe8414463bc0fd # v46.1.15
        with:
          token: ${{ secrets.PAT_RENOVATEBOT }}
          configurationFile: .github/workflows/renovate-config.js
        env:
          RENOVATE_PAT_TOKEN: '${{ secrets.PAT_RENOVATEBOT }}'
          RENOVATE_PLATFORM_COMMIT: 'true'
          RENOVATE_X_GITHUB_HOST_RULES: 'true'
          LOG_LEVEL: debug
